# Generated by Django 4.2.1 on 2023-05-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_comment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
