# Generated by Django 4.2.1 on 2023-05-10 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0005_pagemodel_alter_post_author_alter_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
