# Generated by Django 4.2.1 on 2023-05-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="media/default_image.jpeg", upload_to=""),
        ),
    ]
